BOX_IMAGE = "ubuntu/focal64"
HOST_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.box_check_update = "false"
  config.vm.define "controller" do |controller|
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    controller.vm.box = BOX_IMAGE
    controller.vm.hostname = "controller.ansible.local"
    controller.vm.network :private_network, ip: "192.168.56.250"
    controller.vm.provision "shell", path: "bootstrap.sh"
    controller.vm.provision "file", source: "key_gen.sh", destination: "/home/vagrant/"
  end

  (1..HOST_COUNT).each do |i|
    config.vm.define "host0#{i}" do |hosts|
      hosts.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
      end
      hosts.vm.box = BOX_IMAGE
      hosts.vm.hostname = "host0#{i}.ansible.local"
      hosts.vm.network :private_network, ip: "192.168.56.#{250 + i}"
      hosts.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end